feat: add statefulset

diff --git a/kubectl-check b/kubectl-check
--- a/kubectl-check
+++ b/kubectl-check
@@ -15,6 +15,7 @@ set -o pipefail         # Use last non-zero exit code in a pipeline
 
 trap 'echo "kubectl-check trapped."; exit 1' 1 2 3 15
 
+export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin
 
 ######################################################################################################
 # environment configuration
@@ -22,9 +23,14 @@ trap 'echo "kubectl-check trapped."; exit 1' 1 2 3 15
 kubeconfig="${HOME}/.kube/config" # kubenetes config
 namespace="default"       # kubenetes namespace
 deploy_name=""            # deploy name
-deploy_version=""         # deploy version
+resource_version=""         # deploy version
+statefulset_name=""       # statefulset name
+resource_type=""          # kubenetes resource
+resource_name=""          # kubenetes resource
+resource_version=""          # kubenetes resource
 check_interval=2          # check interval
 check_total=60            # check total
+check_success=3           # check success number
 check_result=false        # check result
 
 
@@ -58,8 +64,8 @@ log() {
 }
 
 function check() {
-  ${kubectl} get pods,deploy >/dev/null 2>1 || (log INFO "[Error] ${COLOR_RED}Please check the configuration of kubectl.${COLOR_OFF}";exit 1)
-  jq -h >/dev/null 2>1 || (log INFO "[Error] ${COLOR_RED}Please check the configuration of jq.${COLOR_OFF}";exit 1)
+  ${kubectl} get pods,deployment,statefulset >/dev/null || (log INFO "[Error] ${COLOR_RED}Please check the configuration of kubectl.${COLOR_OFF}";exit 1)
+  jq -h >/dev/null || (log INFO "[Error] ${COLOR_RED}Please check the configuration of jq.${COLOR_OFF}";exit 1)
 }
 
 function check_parameter {
@@ -77,7 +83,7 @@ function check_pods () {
     local pod_data=$($kubectl get pods "$item" -o json)
     log INFO  "[Pods] ${COLOR_YELLOW}$item${COLOR_OFF}"
     log INFO  "  phase: ${COLOR_GREEN}$(echo $pod_data | jq -r .status.phase)${COLOR_OFF}"
-    log INFO  "  conditions:\n$(echo $pod_data | jq -r '.status.conditions[] | select(.status != "True") | "    status=\(.status), type=\(.type), reason=\(.reason), message=\(.message)"')"
+    log INFO  "  conditions:\n$(echo $pod_data | jq -r '.status.conditions[]? | select(.status != "True") | "    status=\(.status), type=\(.type), reason=\(.reason), message=\(.message)"')"
     log INFO  "  hostIP: $(echo $pod_data | jq -r .status.hostIP)"
     log DEBUG "  podIP: $(echo $pod_data | jq -r .status.podIP)"
     log DEBUG "  qosClass: $(echo $pod_data | jq -r .status.qosClass)"
@@ -86,21 +92,21 @@ function check_pods () {
   done
 }
 
-function check_deploy () {
+function check_deployment () {
   local deploy_name=$*
   local deploy_data
-  deploy_data=$($kubectl get deploy $deploy_name -o json)
+  deploy_data=$($kubectl get deployment $deploy_name -o json)
   if [ "$?" -ne "0" ]; then
     log INFO   "[Error] ${COLOR_RED}Get resource fail.${COLOR_OFF}"
     exit 1
   fi
-  local deploy_sel=$($kubectl get --raw "/apis/apps/v1/namespaces/$namespace/deployments/$deploy_name/scale" | jq -r .status.targetSelector)
+  local deploy_sel=$($kubectl get --raw "/apis/apps/v1/namespaces/$namespace/deployments/$deploy_name/scale" | jq -r .status.selector)
   local deploy_availableReplicas=$(echo $deploy_data | jq -r .status.availableReplicas)
-  local deploy_conditions=$(echo $deploy_data | jq -r '.status.conditions[] | "    status=\(.status), type=\(.type), reason=\(.reason), message=\(.message)"')
+  local deploy_conditions=$(echo $deploy_data | jq -r '.status.conditions[]? | "    status=\(.status), type=\(.type), reason=\(.reason), message=\(.message)"')
   local deploy_replicas=$(echo $deploy_data | jq -r .status.replicas)   # deploy 副本数
   local deploy_unavailableReplicas=$(echo $deploy_data | jq -r .status.unavailableReplicas)    # deploy 不可用副本数
   local deploy_updatedReplicas=$(echo $deploy_data | jq -r .status.updatedReplicas)     # deploy更新副本数 
-  deploy_version=$(echo $deploy_data | jq -r .status.observedGeneration)     # deploy版本号
+  resource_version=$(echo $deploy_data | jq -r .status.observedGeneration)     # deploy版本号
 
   log INFO  "[Deployment] ${COLOR_YELLOW}$deploy_name${COLOR_OFF}"
   log DEBUG "  namespace: ${namespace-}"
@@ -110,14 +116,56 @@ function check_deploy () {
   log DEBUG "  availableReplicas: ${deploy_availableReplicas-}"
   log INFO  "  unavailableReplicas: ${deploy_unavailableReplicas-}"
   log DEBUG "  updatedReplicas: ${deploy_updatedReplicas-}"
-  log DEBUG "  observedGeneration: ${deploy_version-}"
+  log DEBUG "  observedGeneration: ${resource_version-}"
 
   if [[ "${deploy_unavailableReplicas-}" != "null" &&  ${deploy_unavailableReplicas-} -gt 0 ]]; then
-    deploy_pod_name=$($kubectl get pods --selector=$deploy_sel -o json | jq -r '.items[] | select( ([ .status.conditions[] | select(.status == "False" ) ] | length ) != 0) | .metadata.name')
+    deploy_pod_name=$($kubectl get pods --selector=$deploy_sel -o json | jq -r '.items[]? | select( ([ .status.conditions[]? | select(.status == "False" ) ] | length ) != 0) | .metadata.name')
     check_pods $deploy_pod_name
     check_result=false
   else
-    log INFO  "[Deploy] Pod success."
+    log INFO "[Deployment] ${COLOR_GREEN}Pod success.${COLOR_OFF}"
+    check_result=true
+  fi
+}
+
+function check_statefulset () {
+  local statefulset_name=$*
+  local statefulset_data
+  statefulset_data=$($kubectl get statefulset $statefulset_name -o json)
+  if [ "$?" -ne "0" ]; then
+    log INFO   "[Error] ${COLOR_RED}Get resource fail.${COLOR_OFF}"
+    exit 1
+  fi
+  local statefulset_sel=$($kubectl get --raw "/apis/apps/v1/namespaces/$namespace/statefulsets/$statefulset_name/scale" | jq -r .status.selector)
+  local statefulset_availableReplicas=$(echo $statefulset_data | jq -r .status.availableReplicas)
+  local statefulset_replicas=$(echo $statefulset_data | jq -r .status.replicas)   # statefulset 副本数
+  local statefulset_updateRevision=$(echo $statefulset_data | jq -r .status.updatedRevision)     # 
+  local statefulset_updatedReplicas=$(echo $statefulset_data | jq -r .status.updatedReplicas)     # statefulset更新副本数 
+  local statefulset_collisionCount=$(echo $statefulset_data | jq -r .status.collisionCount)     # 
+  local statefulset_currentReplicas=$(echo $statefulset_data | jq -r .status.currentReplicas)     # 
+  local statefulset_currentRevision=$(echo $statefulset_data | jq -r .status.currentRevision)     # 
+  local statefulset_readyReplicas=$(echo $statefulset_data | jq -r .status.readyReplicas)     # 
+  resource_version=$(echo $statefulset_data | jq -r .status.observedGeneration)     # statefulset版本号
+
+  log INFO  "[StatefulSet] ${COLOR_YELLOW}${statefulset_name}${COLOR_OFF}"
+  log DEBUG "  namespace: ${namespace-}"
+  log DEBUG "  selector: ${statefulset_sel-}"
+  log INFO  "  replicas: ${statefulset_replicas-}"
+  log INFO  "  readyReplicas: ${statefulset_readyReplicas-}"
+  log DEBUG "  collisionCount: ${statefulset_collisionCount-}"
+  log INFO  "  availableReplicas: ${statefulset_availableReplicas-}"
+  log INFO  "  updateRevision: ${statefulset_updateRevision-}"
+  log INFO  "  updatedReplicas: ${statefulset_updatedReplicas-}"
+  log INFO  "  currentRevision: ${statefulset_currentRevision-}"
+  log INFO  "  currentReplicas: ${statefulset_currentReplicas-}"
+  log DEBUG "  observedGeneration: ${resource_version-}"
+
+  if [[ "${statefulset_replicas:-0}" != "${statefulset_readyReplicas:-1}" || "${statefulset_replicas:-0}" != "${statefulset_updatedReplicas:-0}" ]]; then
+    statefulset_pod_name=$($kubectl get pods --selector=$statefulset_sel -o json | jq -r '.items[]? | select( ([ .status.conditions[]? | select(.status == "False" ) ] | length ) != 0) | .metadata.name')
+    check_pods $statefulset_pod_name
+    check_result=false
+  else
+    log INFO "[StatefulSet] ${COLOR_GREEN}Pod success.${COLOR_OFF}"
     check_result=true
   fi
 }
@@ -130,9 +178,11 @@ function usage {
     echo "Options:"
     echo "  -c,--kubeconfig    Specify kubeconfig, default is ${HOME}/.kube/config"
     echo "  -n,--namespace     Specify namespace, default is default"
-    echo "  -d,--deploy        Depoyment name"
+    echo "  -d,--deployment    Depoyment name"
+    echo "  -s,--statefulset   StatefulSet name"
     echo "  -i,--interval      Check the deployment status interval"
     echo "  -t,--total         Total number of inspections"
+    echo "  -sn,--success      Total number of success"
     echo "  -v,--verbose       Verbose info"
     echo "  --nocolor          Do not output color"
     echo "  -h,--help          View help"
@@ -156,14 +206,22 @@ while [ "${1-}" != "" ]; do
         -n | --namespace )          shift
                                     namespace=${1:-}
                                     ;;
-        -d | --deploy )             shift
-                                    deploy_name=${1-}
+        -d | --deployment )         shift
+                                    resource_name=${1-}
+                                    resource_type="deployment"
+                                    ;;
+        -s | --statefulset )        shift
+                                    resource_name=${1-}
+                                    resource_type="statefulset"
                                     ;;
         -i | --interval )           shift
                                     check_interval=${1-}
                                     ;;
         -t | --total )              shift
                                     check_total=${1-}
+                                    ;;
+        -sn | --success )           shift
+                                    check_success=${1-}
                                     ;;
         -v | --verbose )            script_logging_level=DEBUG
                                     ;;
@@ -189,37 +247,41 @@ if [ "${nocolor-}" == "true" ]; then
 fi
 
 check
-check_parameter deploy_name
+check_parameter resource_name
 
+success_number=0
 for (( i=1; i<=check_total; i++ ))
 do
    log INFO "[Number of inspections] ${COLOR_BLUE}$i${COLOR_OFF}"
    log INFO "[Time] ${COLOR_BLUE}$(date +'%Y-%m-%d %H:%M:%S')${COLOR_OFF}"
    [ $i -eq $check_total ] && script_logging_level=DEBUG
-   check_deploy $deploy_name
+   check_${resource_type} $resource_name
    if [ $check_result == true ]; then
-     break
+     success_number=$((success_number+1))
+     [[ ${success_number:-0} -ge ${check_success:-0} ]] && break
+     check_result=false
    else
-     log INFO "[Reuslt] ${COLOR_RED}Deployment is not ready.${COLOR_OFF}"
-     [ $i -ne $check_total ] && (log INFO "[Sleep] ${check_interval}s";sleep $check_interval)
-     log INFO
+     log INFO "[Reuslt] ${COLOR_RED}${resource_type^} is not ready.${COLOR_OFF}"
    fi
+   [ $i -ne $check_total ] && (log INFO "[Sleep] ${check_interval}s";sleep $check_interval)
+   log INFO
 done
 
-if [[ ${deploy_version:-} -gt 1 && ${script_logging_level} == "DEBUG" ]]; then
+if [[ ${resource_version:-} -gt 0 && ${script_logging_level} == "DEBUG" ]]; then
   log DEBUG [Version comparison]
   set +o errexit 
   if [ "${nocolor-}" == "true" ]; then
-    diff -u <($kubectl rollout history deploy/${deploy_name:-} --revision=$(($deploy_version-1))) \
-      <($kubectl rollout history deploy/${deploy_name:-} --revision=${deploy_version:-})
+    diff -u <($kubectl rollout history ${resource_type:-}/${resource_name:-} --revision=$(($resource_version-1))) \
+      <($kubectl rollout history ${resource_type:-}/${resource_name:-} --revision=${resource_version:-})
   else
     export TERM=xterm-256color
-    diff -u <($kubectl rollout history deploy/${deploy_name:-} --revision=$(($deploy_version-1))) \
-      <($kubectl rollout history deploy/${deploy_name:-} --revision=${deploy_version:-}) \
+    diff -u <($kubectl rollout history ${resource_type:-}/${resource_name:-} --revision=$(($resource_version-1))) \
+      <($kubectl rollout history ${resource_type:-}/${resource_name:-} --revision=${resource_version:-}) \
       |  sed "s/^-/$(tput setaf 1)&/; s/^+/$(tput setaf 2)&/; s/^@/$(tput setaf 6)&/; s/$/$(tput sgr0)/"
   fi
 fi
 
+log INFO
 if [ $check_result == true ]; then
   log INFO "[Reuslt] ${COLOR_GREEN}Deploy success.${COLOR_OFF}"
   exit 0
